@echo off
echo Checking for processes on port 5241...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :5241 ^| findstr LISTENING') do (
    echo Killing process %%a...
    taskkill /PID %%a /F >nul 2>&1
)
timeout /t 1 /nobreak >nul
echo Starting dev server...
call npm run start:dev
